"""initial portfolio schema

Revision ID: d7ef7721679c
Revises: 
Create Date: 2026-09-15 11:45:09.359065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7ef7721679c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(name)) > 0', name='ck_categories_name_not_empty'),
    sa.CheckConstraint('char_length(trim(slug)) > 0', name='ck_categories_slug_not_empty'),
    sa.CheckConstraint('sort_order >= 0', name='ck_categories_sort_order_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('profiles',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('bio_short', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_profiles_status'),
    sa.CheckConstraint('char_length(trim(display_name)) > 0', name='ck_profiles_display_name_not_empty'),
    sa.CheckConstraint('char_length(trim(slug)) > 0', name='ck_profiles_slug_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_slug'), 'profiles', ['slug'], unique=True)
    op.create_table('skills',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(name)) > 0', name='ck_skills_name_not_empty'),
    sa.CheckConstraint('char_length(trim(slug)) > 0', name='ck_skills_slug_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('tags',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(name)) > 0', name='ck_tags_name_not_empty'),
    sa.CheckConstraint('char_length(trim(slug)) > 0', name='ck_tags_slug_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('achievements',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(title)) > 0', name='ck_achievements_title_not_empty'),
    sa.CheckConstraint('sort_order >= 0', name='ck_achievements_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_profile_id'), 'achievements', ['profile_id'], unique=False)
    op.create_index('ix_achievements_profile_id_sort_order', 'achievements', ['profile_id', 'sort_order'], unique=False)
    op.create_table('certifications',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('credential_url', sa.String(length=2048), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(issuer)) > 0', name='ck_certifications_issuer_not_empty'),
    sa.CheckConstraint('char_length(trim(name)) > 0', name='ck_certifications_name_not_empty'),
    sa.CheckConstraint('expires_on IS NULL OR issued_on IS NULL OR expires_on >= issued_on', name='ck_certifications_date_range'),
    sa.CheckConstraint('sort_order >= 0', name='ck_certifications_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_profile_id'), 'certifications', ['profile_id'], unique=False)
    op.create_index('ix_certifications_profile_id_sort_order', 'certifications', ['profile_id', 'sort_order'], unique=False)
    op.create_index('uq_certifications_profile_id_credential_id', 'certifications', ['profile_id', 'credential_id'], unique=True, postgresql_where=sa.text('credential_id IS NOT NULL'))
    op.create_table('education',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(institution)) > 0', name='ck_education_institution_not_empty'),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_education_date_range'),
    sa.CheckConstraint('sort_order >= 0', name='ck_education_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_profile_id'), 'education', ['profile_id'], unique=False)
    op.create_index('ix_education_profile_id_sort_order', 'education', ['profile_id', 'sort_order'], unique=False)
    op.create_table('experiences',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_current = false) OR (end_date IS NULL)', name='ck_experiences_current_end_date'),
    sa.CheckConstraint('char_length(trim(company_name)) > 0', name='ck_experiences_company_name_not_empty'),
    sa.CheckConstraint('char_length(trim(title)) > 0', name='ck_experiences_title_not_empty'),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_experiences_date_range'),
    sa.CheckConstraint('sort_order >= 0', name='ck_experiences_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_profile_id'), 'experiences', ['profile_id'], unique=False)
    op.create_index('ix_experiences_profile_id_sort_order', 'experiences', ['profile_id', 'sort_order'], unique=False)
    op.create_table('profile_links',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('github', 'linkedin', 'x', 'website', 'email', 'other')", name='ck_profile_links_kind'),
    sa.CheckConstraint('char_length(trim(url)) > 0', name='ck_profile_links_url_not_empty'),
    sa.CheckConstraint('sort_order >= 0', name='ck_profile_links_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'url', name='uq_profile_links_profile_id_url')
    )
    op.create_index(op.f('ix_profile_links_profile_id'), 'profile_links', ['profile_id'], unique=False)
    op.create_index('ix_profile_links_profile_id_sort_order', 'profile_links', ['profile_id', 'sort_order'], unique=False)
    op.create_table('projects',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_projects_status'),
    sa.CheckConstraint('char_length(trim(slug)) > 0', name='ck_projects_slug_not_empty'),
    sa.CheckConstraint('char_length(trim(title)) > 0', name='ck_projects_title_not_empty'),
    sa.CheckConstraint('ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on', name='ck_projects_date_range'),
    sa.CheckConstraint('sort_order >= 0', name='ck_projects_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'slug', name='uq_projects_profile_id_slug')
    )
    op.create_index(op.f('ix_projects_profile_id'), 'projects', ['profile_id'], unique=False)
    op.create_index('ix_projects_profile_id_sort_order', 'projects', ['profile_id', 'sort_order'], unique=False)
    op.create_index('ix_projects_profile_id_sort_order_featured', 'projects', ['profile_id', 'sort_order'], unique=False, postgresql_where=sa.text('is_featured = true'))
    op.create_index('ix_projects_profile_id_status', 'projects', ['profile_id', 'status'], unique=False)
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_experience_skills_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'skill_id', name='uq_experience_skills_experience_id_skill_id')
    )
    op.create_index(op.f('ix_experience_skills_experience_id'), 'experience_skills', ['experience_id'], unique=False)
    op.create_index('ix_experience_skills_experience_id_sort_order', 'experience_skills', ['experience_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_experience_skills_skill_id'), 'experience_skills', ['skill_id'], unique=False)
    op.create_table('project_categories',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_project_categories_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'category_id', name='uq_project_categories_project_id_category_id')
    )
    op.create_index(op.f('ix_project_categories_category_id'), 'project_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_project_categories_project_id'), 'project_categories', ['project_id'], unique=False)
    op.create_index('ix_project_categories_project_id_sort_order', 'project_categories', ['project_id', 'sort_order'], unique=False)
    op.create_table('project_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('github', 'live_demo', 'docs', 'package', 'other')", name='ck_project_links_kind'),
    sa.CheckConstraint('char_length(trim(url)) > 0', name='ck_project_links_url_not_empty'),
    sa.CheckConstraint('sort_order >= 0', name='ck_project_links_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'url', name='uq_project_links_project_id_url')
    )
    op.create_index(op.f('ix_project_links_project_id'), 'project_links', ['project_id'], unique=False)
    op.create_index('ix_project_links_project_id_sort_order', 'project_links', ['project_id', 'sort_order'], unique=False)
    op.create_table('project_media',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('image', 'video', 'diagram')", name='ck_project_media_kind'),
    sa.CheckConstraint('char_length(trim(url)) > 0', name='ck_project_media_url_not_empty'),
    sa.CheckConstraint('sort_order >= 0', name='ck_project_media_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_media_project_id'), 'project_media', ['project_id'], unique=False)
    op.create_index('ix_project_media_project_id_sort_order', 'project_media', ['project_id', 'sort_order'], unique=False)
    op.create_index('uq_project_media_one_primary', 'project_media', ['project_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('project_skills',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_project_skills_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'skill_id', name='uq_project_skills_project_id_skill_id')
    )
    op.create_index(op.f('ix_project_skills_project_id'), 'project_skills', ['project_id'], unique=False)
    op.create_index('ix_project_skills_project_id_sort_order', 'project_skills', ['project_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_project_skills_skill_id'), 'project_skills', ['skill_id'], unique=False)
    op.create_table('project_tags',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tag_id', name='uq_project_tags_project_id_tag_id')
    )
    op.create_index(op.f('ix_project_tags_project_id'), 'project_tags', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_tags_tag_id'), 'project_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_tags_tag_id'), table_name='project_tags')
    op.drop_index(op.f('ix_project_tags_project_id'), table_name='project_tags')
    op.drop_table('project_tags')
    op.drop_index(op.f('ix_project_skills_skill_id'), table_name='project_skills')
    op.drop_index('ix_project_skills_project_id_sort_order', table_name='project_skills')
    op.drop_index(op.f('ix_project_skills_project_id'), table_name='project_skills')
    op.drop_table('project_skills')
    op.drop_index('uq_project_media_one_primary', table_name='project_media', postgresql_where=sa.text('is_primary = true'))
    op.drop_index('ix_project_media_project_id_sort_order', table_name='project_media')
    op.drop_index(op.f('ix_project_media_project_id'), table_name='project_media')
    op.drop_table('project_media')
    op.drop_index('ix_project_links_project_id_sort_order', table_name='project_links')
    op.drop_index(op.f('ix_project_links_project_id'), table_name='project_links')
    op.drop_table('project_links')
    op.drop_index('ix_project_categories_project_id_sort_order', table_name='project_categories')
    op.drop_index(op.f('ix_project_categories_project_id'), table_name='project_categories')
    op.drop_index(op.f('ix_project_categories_category_id'), table_name='project_categories')
    op.drop_table('project_categories')
    op.drop_index(op.f('ix_experience_skills_skill_id'), table_name='experience_skills')
    op.drop_index('ix_experience_skills_experience_id_sort_order', table_name='experience_skills')
    op.drop_index(op.f('ix_experience_skills_experience_id'), table_name='experience_skills')
    op.drop_table('experience_skills')
    op.drop_index('ix_projects_profile_id_status', table_name='projects')
    op.drop_index('ix_projects_profile_id_sort_order_featured', table_name='projects', postgresql_where=sa.text('is_featured = true'))
    op.drop_index('ix_projects_profile_id_sort_order', table_name='projects')
    op.drop_index(op.f('ix_projects_profile_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_profile_links_profile_id_sort_order', table_name='profile_links')
    op.drop_index(op.f('ix_profile_links_profile_id'), table_name='profile_links')
    op.drop_table('profile_links')
    op.drop_index('ix_experiences_profile_id_sort_order', table_name='experiences')
    op.drop_index(op.f('ix_experiences_profile_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index('ix_education_profile_id_sort_order', table_name='education')
    op.drop_index(op.f('ix_education_profile_id'), table_name='education')
    op.drop_table('education')
    op.drop_index('uq_certifications_profile_id_credential_id', table_name='certifications', postgresql_where=sa.text('credential_id IS NOT NULL'))
    op.drop_index('ix_certifications_profile_id_sort_order', table_name='certifications')
    op.drop_index(op.f('ix_certifications_profile_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index('ix_achievements_profile_id_sort_order', table_name='achievements')
    op.drop_index(op.f('ix_achievements_profile_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_profiles_slug'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
